-- CreateTable
CREATE TABLE `Metricas` (
    `id` VARCHAR(191) NOT NULL,
    `ticket_diaria` DOUBLE NOT NULL,
    `receita_com_taxas` DOUBLE NOT NULL,
    `taxas` DOUBLE NOT NULL,
    `taxa_de_limpeza` DOUBLE NOT NULL,
    `taxa_enxoval` DOUBLE NOT NULL,
    `taxa_parcelamento` DOUBLE NOT NULL,
    `taxa_cafe` DOUBLE NOT NULL,
    `comissao` DOUBLE NOT NULL,
    `nota` DOUBLE NOT NULL,
    `data_dia` INTEGER NOT NULL,
    `data_mes` INTEGER NOT NULL,
    `nome_mes` VARCHAR(191) NOT NULL,
    `data_ano` INTEGER NOT NULL,
    `dia_chegada` VARCHAR(191) NOT NULL,
    `dia_saida` VARCHAR(191) NOT NULL,
    `numero_noites` INTEGER NOT NULL,
    `DDD` VARCHAR(191) NOT NULL,
    `hospedes` INTEGER NOT NULL,
    `id_agente` VARCHAR(191) NOT NULL,
    `nome_agente` VARCHAR(191) NOT NULL,
    `canais` VARCHAR(191) NOT NULL,
    `data_dia_criacao` INTEGER NOT NULL,
    `data_mes_criacao` VARCHAR(191) NOT NULL,
    `data_ano_criacao` INTEGER NOT NULL,
    `siglas_condominios` VARCHAR(191) NOT NULL,
    `estado` VARCHAR(191) NOT NULL,
    `cidade` VARCHAR(191) NOT NULL,
    `regiao` VARCHAR(191) NOT NULL,
    `rua_numero` VARCHAR(191) NOT NULL,
    `imovel` VARCHAR(191) NOT NULL,
    `status` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
